version: "3"

services:
  re_water_mysql:
    container_name: re_water_mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'rewater_mysql'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1@23'
      MYSQL_ROOT_PASSWORD: 'root'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3309:3306
    volumes:
      - ../mysql/lib:/var/lib/mysql
    restart: on-failure
    networks:
      - local_rewater

  app_rewater:
    container_name: app_rewater
    build:
      dockerfile: ./builds/Dockerfile
      context: .
    image: image_app_rewater:latest
    env_file: ./.env
    ports:
      - "8000:8000"
      - "3030:3030"
    restart: on-failure
    volumes:
      - ./:/opt/app/re_water
    tty: true
    stdin_open: true
    depends_on:
      - re_water_mysql
    networks:
      local_rewater:
    command: bash -c "alembic upgrade head && gunicorn main:app --workers=4 --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    # command: bash -c "python main.py"

networks:
  local_rewater:
    driver: bridge
